function p = pathdef
%PATHDEF Search path defaults.
%   PATHDEF returns a string that can be used as input to MATLABPATH
%   in order to set the path.

  
%   Copyright 1984-2000 The MathWorks, Inc.
%   $Revision: 1.4 $ $Date: 2000/06/01 16:19:21 $

% PATH DEFINED HERE -- Don't change this line.

p = [...
'/home/math/heryudon/research_summer2003/sc:',...
'/home/math/heryudon/research_summer2003/oop:',...
'/home/math/heryudon/research_summer2003/oop/scprivate:',...
'/home/math/heryudon/matlab:',...
matlabroot,'/toolbox/matlab/general:',...
matlabroot,'/toolbox/matlab/ops:',...
matlabroot,'/toolbox/matlab/lang:',...
matlabroot,'/toolbox/matlab/elmat:',...
matlabroot,'/toolbox/matlab/elfun:',...
matlabroot,'/toolbox/matlab/specfun:',...
matlabroot,'/toolbox/matlab/matfun:',...
matlabroot,'/toolbox/matlab/datafun:',...
matlabroot,'/toolbox/matlab/audio:',...
matlabroot,'/toolbox/matlab/polyfun:',...
matlabroot,'/toolbox/matlab/funfun:',...
matlabroot,'/toolbox/matlab/sparfun:',...
matlabroot,'/toolbox/matlab/graph2d:',...
matlabroot,'/toolbox/matlab/graph3d:',...
matlabroot,'/toolbox/matlab/specgraph:',...
matlabroot,'/toolbox/matlab/graphics:',...
matlabroot,'/toolbox/matlab/uitools:',...
matlabroot,'/toolbox/matlab/strfun:',...
matlabroot,'/toolbox/matlab/iofun:',...
matlabroot,'/toolbox/matlab/timefun:',...
matlabroot,'/toolbox/matlab/datatypes:',...
matlabroot,'/toolbox/matlab/verctrl:',...
matlabroot,'/toolbox/matlab/demos:',...
matlabroot,'/toolbox/local:',...
matlabroot,'/toolbox/simulink/simulink:',...
matlabroot,'/toolbox/simulink/blocks:',...
matlabroot,'/toolbox/simulink/components:',...
matlabroot,'/toolbox/simulink/fixedandfloat:',...
matlabroot,'/toolbox/simulink/fixedandfloat/fxpdemos:',...
matlabroot,'/toolbox/simulink/fixedandfloat/obsolete:',...
matlabroot,'/toolbox/simulink/simdemos:',...
matlabroot,'/toolbox/simulink/simdemos/aerospace:',...
matlabroot,'/toolbox/simulink/simdemos/automotive:',...
matlabroot,'/toolbox/simulink/simdemos/simfeatures:',...
matlabroot,'/toolbox/simulink/simdemos/simgeneral:',...
matlabroot,'/toolbox/simulink/simdemos/simnew:',...
matlabroot,'/toolbox/simulink/dee:',...
matlabroot,'/toolbox/simulink/dastudio:',...
matlabroot,'/toolbox/stateflow/stateflow:',...
matlabroot,'/toolbox/stateflow/sfdemos:',...
matlabroot,'/toolbox/stateflow/coder:',...
matlabroot,'/toolbox/rtw/rtw:',...
matlabroot,'/toolbox/rtw/rtwdemos:',...
matlabroot,'/toolbox/rtw/rtwdemos/rsimdemos:',...
matlabroot,'/toolbox/rtw/targets/asap2/asap2:',...
matlabroot,'/toolbox/rtw/targets/asap2/asap2/user:',...
matlabroot,'/toolbox/comm/comm:',...
matlabroot,'/toolbox/comm/commdemos:',...
matlabroot,'/toolbox/comm/commobsolete:',...
matlabroot,'/toolbox/commblks/commblks:',...
matlabroot,'/toolbox/commblks/commmasks:',...
matlabroot,'/toolbox/commblks/commmex:',...
matlabroot,'/toolbox/commblks/commblksdemos:',...
matlabroot,'/toolbox/commblks/commblksobsolete/commblksobsolete:',...
matlabroot,'/toolbox/compiler:',...
matlabroot,'/toolbox/control/control:',...
matlabroot,'/toolbox/control/ctrlguis:',...
matlabroot,'/toolbox/control/ctrlobsolete:',...
matlabroot,'/toolbox/control/ctrlutil:',...
matlabroot,'/toolbox/control/ctrldemos:',...
matlabroot,'/toolbox/database/database:',...
matlabroot,'/toolbox/database/dbdemos:',...
matlabroot,'/toolbox/database/vqb:',...
matlabroot,'/toolbox/dspblks/dspblks:',...
matlabroot,'/toolbox/dspblks/dspmasks:',...
matlabroot,'/toolbox/dspblks/dspmex:',...
matlabroot,'/toolbox/dspblks/dspdemos:',...
matlabroot,'/toolbox/fuzzy/fuzzy:',...
matlabroot,'/toolbox/fuzzy/fuzdemos:',...
matlabroot,'/toolbox/ident/ident:',...
matlabroot,'/toolbox/ident/idobsolete:',...
matlabroot,'/toolbox/ident/idguis:',...
matlabroot,'/toolbox/ident/idutils:',...
matlabroot,'/toolbox/ident/iddemos:',...
matlabroot,'/toolbox/ident/idhelp:',...
matlabroot,'/toolbox/images/images:',...
matlabroot,'/toolbox/images/imdemos:',...
matlabroot,'/toolbox/lmi/lmictrl:',...
matlabroot,'/toolbox/lmi/lmilab:',...
matlabroot,'/toolbox/mpc/mpccmds:',...
matlabroot,'/toolbox/mpc/mpcdemos:',...
matlabroot,'/toolbox/mutools/commands:',...
matlabroot,'/toolbox/mutools/subs:',...
matlabroot,'/toolbox/nnet/nnet:',...
matlabroot,'/toolbox/nnet/nnutils:',...
matlabroot,'/toolbox/nnet/nncontrol:',...
matlabroot,'/toolbox/nnet/nndemos:',...
matlabroot,'/toolbox/nnet/nnobsolete:',...
matlabroot,'/toolbox/optim:',...
matlabroot,'/toolbox/pde:',...
matlabroot,'/toolbox/robust:',...
matlabroot,'/toolbox/sb2sl:',...
matlabroot,'/toolbox/signal/signal:',...
matlabroot,'/toolbox/signal/sigtools:',...
matlabroot,'/toolbox/signal/sptoolgui:',...
matlabroot,'/toolbox/signal/sigdemos:',...
matlabroot,'/toolbox/stats:',...
matlabroot,'/toolbox/symbolic:',...
matlabroot,'/toolbox/wavelet/wavelet:',...
matlabroot,'/toolbox/wavelet/wavedemo:',...
     ...
];

p = [userpath,p];
